name: ecom_sales
channels:
  - conda-forge
dependencies:
  - python==3.9.15
  - pandas==1.5.2
  - boto3==1.24.80
  - make==4.3
  - pgcli==3.5.0
  - sqlalchemy==1.4.46
  - psycopg2-binary==2.9.3
  - jupyter==1.0.0
  # Pip
  - pip==22.3.1
  - pip: